### ISSUE TITLE
Can you please help in compiling latest libcuckoo on windows

### ISSUE THREAD

**Issue by necromancersecret** [WheelofTime/libcuckoo-windows#1]
Hello 

Can you please help me in compiling latest libcuckoo on windows ?

Neo

**Comment by necromancersecret** [comment]
Please , i have been using your build but issue "https://github.com/efficient/libcuckoo/issues/57"
This same have been provided in latest libcuckoo.. Can you please help me in compiling the latest one 

Neo

**Comment by LitingLin** [comment]
I think they have supported windows now, you can use the official repo directly.
